### PR TITLE
Set proper env variable for postgres backups

### PR DESCRIPTION
**Pull request by Tomatosoup97**
This change is critical, since without setting this env variable, postgres
backups were broken, and no information in README was provided about that.

### CODE REVIEW

**Comment by Tomatosoup97** [comment]
@esmail @jnm

**Comment by janknobloch** [comment]
@esmail @jnm @Tomatosoup97 
It seems this is even worse than anticipated as it tricked me for a while. The env variable should be set through the envfiles/kobocat.txt however it is not set inside the postgres container..


Steps to reproduce:
1. pull github repo
2. update settings in server.env
3. place symlink for server.env
4. boot up containers
5. access postgres container exec -it /bin/bash
6. printenvs -> KOBO_POSTGRES_DB_NAME not set therefore backups only running on the postgres database.

so you are right @Tomatosoup97 your fix seem to work to similar to setting the env directly in the container using `export KOBO_POSTGRES_DB_NAME=kobotoolbox`

But i think the main issue is that it should be set in first place using kobocat.txt

I thinks this is one of the most important issues to fix as it tricks people in having a functional backup which is not the case..

**Comment by lucernae** [comment]
Hi @Tomatosoup97 @janknobloch @jnm. This is an old PR, so I wonder if this is still maintained.
I just want to add some comments, I found out the backup scripts were executed by cronjob. So, even though you set up 
`KOBO_POSTGRES_DB_NAME` in the container, cron will not have them.
We have to export this env var in the cron schedule so the script can have them.

**Comment by noliveleger** [comment]
With latest version of `kobo-docker`, backups scripts have changed and they should work as expected. 

For ref: https://github.com/kobotoolbox/kobo-docker#backups

**Pull request closed without merging**
