### PR TITLE
Restart containers on reboot

### PR DESCRIPTION
**Pull request by Tomatosoup97**

### CODE REVIEW

**Comment by Tomatosoup97** [comment]
@esmail

**Comment by noliveleger** [comment]
@jnm what do you think of this? 
I think we should have to change the dependencies between `kobocat` and `kpi` (e.g. (`kobocat` waits for `kpi` to be ready in order to boot as well) to apply this change.

**Comment by roemhildtg** [comment]
I noticed recently that when I reboot the server with kobo-docker installed (installed from kobo-installer) I need to re-run the run.py to get everything up again. This search lead me here. Is this something that is required for now?

**Comment by noliveleger** [comment]
> I noticed recently that when I reboot the server with kobo-docker installed (installed from kobo-installer) I need to re-run the run.py to get everything up again. This search lead me here. Is this something that is required for now?

Indeed.

**Comment by jnm** [comment]
@noliveleger, I'm in favor of using `unless-stopped` or `always`. For a server, I'd lean toward `always`:
> Always restart the container if it stops. If it is manually stopped, it is restarted only when Docker daemon restarts or the container itself is manually restarted.

As a developer, I'd prefer `unless-stopped` on my local machine:
> `Similar to always, except that when the container is stopped (manually or otherwise), it is not restarted even after Docker daemon restarts.`

That said, as a developer, I can change it myself—and we can use `always` in this repository. What do you think?

Descriptions of `restart` values: https://docs.docker.com/config/containers/start-containers-automatically/

**Pull request closed without merging**
