### PR TITLE
Update envfile.server.txt

### PR DESCRIPTION
**Pull request by grueneedv**
Added examples for easier setup

### CODE REVIEW

**Comment by esmail** [comment]
@grueneedv, thanks for the PR. I have a couple related changes I'd like to include before merging; would you mind turning on [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by grueneedv** [comment]
No, feel free merge it when you're ready.

Am 08.03.2017 um 17:27 schrieb Esmail:
> @grueneedv, thanks for the PR. I have a couple related changes I'd like to include before merging; would you mind turning on [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?
>

**Comment by esmail** [comment]
Thanks :)

**Comment by esmail** [comment]
Okay; all done. Sorry for mucking about in your `master` branch. Does this still capture your original intent @grueneedv?

**Comment by grueneedv** [comment]
Yes, intend was to lower the entry barrier for new installations. With examples much better.

**Comment by grueneedv** [comment]
Oops accidentially clicked the wrong button.

**Comment by dorey** [comment]
No worries!

**Comment by esmail** [comment]
Oh; I get it now. @dorey, I think `grueneedv` meant they clicked the wrong button when closing the issue, not reopening it, and I mistakenly thought you'd merged rather than closed it. All's well now.

**Pull request merged**
